@echo off
echo Building Zytherion Blockchain...

echo Step 1: Cleaning up...
docker-compose down
docker system prune -f

echo Step 2: Building Docker images...
docker-compose build --no-cache

echo Step 3: Starting services...
docker-compose up -d

echo Step 4: Checking status...
docker-compose ps

echo Step 5: Viewing logs...
docker-compose logs -f